[project]
name = "varch"
version = "0.1.0"

dependencies = [
    "typer",
    "torch",
    "open-clip-torch",
    "faiss-cpu",
    "transformers>=4.57.0",
    "qwen-vl-utils[decord]>=0.0.14",
    "accelerate",
    "tqdm",
    "pillow",
    "numpy",
    "bitsandbytes>=0.46.1",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
varch = "varch.cli:main"
